### ISSUE TITLE
Character recommendations

### ISSUE THREAD

**Issue by aaronbell** [3type/glyphs-han#1]
Thank you for all your hard work in putting together these character lists!

I had a question about how to best make use of these character lists. In particular, do you recommend making use of the "Regional" character lists, or the established character sets, or a mix of both? So if I wanted to create a Traditional Chinese font, is it enough to support the Taiwan Frequent / Less Common sets, or should I also look to add the rest of Big5 (a difference of about 1800 characters)? Similarly, for China Mainland is supporting all "General Standard Characters" sufficient?

Also, what is the relationship between the base set "Fundamental" / "Commonly used online" and the Regional ranges? 

Any advice would be great! Thank you :)

**Comment by stone-zeng** [comment]
Hi! As far as I know, most foundries in China Mainland will use **GB 2312** as the basic character set (6763 chars) for their fonts. For some special uses such as newspapers, textbooks and dictionaries, they will use the other much larger char set. For Traditional Chinese fonts, I don't have too much research, but I think most of them will use **Big 5**.

The **Fundamental** characters are from Glyphs 2, and I'm not very sure where are they from. In this [answer](https://www.zhihu.com/question/21232157/answer/17597582) you may find that Julius Hui listed the 12 chars (traditional), but there's no more further reference either.

The **Commonly Used on Internet** is the char set used in some of Hanyi's fonts. It is a supplement of GB 2312, since the latter is somehow outdated and lacks some "new" chars.

These two things has different background and usage of the regional ranges, and actually what range you should use is dependent on your goal, motivation and business consideration. So the ranges listed here (and in Glyphs 2) is for reference only.

**Comment by aaronbell** [comment]
Thank you so much for all the information and recommendations! This is super useful. Cheers.
